server:
  port: 2002

spring:
  application:
    name: SpringCloud-customer-feign-dept-2002

eureka:
  client:
    register-with-eureka: false # 不向eureka注册自己
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka/,http://eureka3003.com:3003/eureka/

